In [ ]:
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense        
from tensorflow.keras.optimizers import Adam   


In [ ]:

wine_data = load_wine() 
 

print('Example data: ')
print(wine_data.data[:5])
print('Example labels: ')
print(wine_data.target[:5])


Example data: 
[[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]]
Example labels: 
[0 0 0 0 0]


In [ ]:


x = wine_data.data 
y_ = wine_data.target.reshape(-1, 1) 
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)


In [ ]:
print(y[:5]) 

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [ ]:

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)
train_x.shape, test_x.shape, train_y.shape, test_y.shape

((142, 13), (36, 13), (142, 3), (36, 3))

In [ ]:


model = Sequential()

model.add(Dense(10, input_shape=(13,), activation='relu', name='fc1'))   
model.add(Dense(10, activation='relu', name='fc2'))                             
model.add(Dense(3, activation='softmax', name='output'))                  


optimizer = Adam(lr=0.001)                                                                
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'] )

print('Neural Network Model Summary: ')
print(model.summary())


Neural Network Model Summary: 
Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 fc1 (Dense)                 (None, 10)                140       
                                                                 
 fc2 (Dense)                 (None, 10)                110       
                                                                 
 output (Dense)              (None, 3)                 33        
                                                                 
Total params: 283
Trainable params: 283
Non-trainable params: 0
_________________________________________________________________
None


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
model.fit(train_x, train_y, verbose=1, batch_size=70, epochs=350)



Epoch 1/350
3/3 [==============================] - 0s 5ms/step - loss: 0.1258 - accuracy: 0.9366
Epoch 2/350
3/3 [==============================] - 0s 5ms/step - loss: 0.1259 - accuracy: 0.9366
Epoch 3/350
3/3 [==============================] - 0s 6ms/step - loss: 0.1255 - accuracy: 0.9366
Epoch 4/350
3/3 [==============================] - 0s 6ms/step - loss: 0.1252 - accuracy: 0.9366
Epoch 5/350
3/3 [==============================] - 0s 5ms/step - loss: 0.1259 - accuracy: 0.9366
Epoch 6/350
3/3 [==============================] - 0s 4ms/step - loss: 0.1254 - accuracy: 0.9366
Epoch 7/350
3/3 [==============================] - 0s 6ms/step - loss: 0.1259 - accuracy: 0.9366
Epoch 8/350
3/3 [==============================] - 0s 5ms/step - loss: 0.1266 - accuracy: 0.9437
Epoch 9/350
3/3 [==============================] - 0s 4ms/step - loss: 0.1259 - accuracy: 0.9366
Epoch 10/350
3/3 [==============================] - 0s 5ms/step - loss: 0.1269 - accuracy: 0.9507
Epoch 11/350
3/3 [===========

In [ ]:

loss, accuracy = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(loss))
print('Final test set accuracy: {:4f}'.format(accuracy))

2/2 [==============================] - 0s 6ms/step - loss: 0.1541 - accuracy: 0.9167
Final test set loss: 0.154110
Final test set accuracy: 0.916667
